insert into badmintonspeler values (1,  'Thomas',     'Thackray',       1303390);
insert into badmintonspeler values (2,  'Pieter',     'van Gils',       118980);
insert into badmintonspeler values (3,  'Leon',       'Bos',            128046);
insert into badmintonspeler values (4,  'Elisa',      'Plat',           208701);
insert into badmintonspeler values (5,  'Roos',       'Hofman',         209109);
insert into badmintonspeler values (6,  'Reitse',     'Terpstra',       128897);
insert into badmintonspeler values (7,  'Hein',       'Dellebarre',     136868);
insert into badmintonspeler values (8,  'Johan',      'Drenthen',       119517);
insert into badmintonspeler values (9,  'Eleni',      'Tjaberings',     134783);
insert into badmintonspeler values (10, 'Danielle',   'Snaathorst',     132288);
insert into badmintonspeler values (11, 'Thijmen',    'de Roo',         208703);
insert into badmintonspeler values (12, 'Marcel',     'Schutte',        1980135);
insert into badmintonspeler values (13, 'Anouk',      'Kalk',           2719151);
insert into badmintonspeler values (14, 'Jonne',      'Ritzen',         1303504);
insert into badmintonspeler values (15, 'Marieke',    'Holt-Elgersma',  119494);
insert into badmintonspeler values (16, 'Carla',      'Oldenburger',    119560);
insert into badmintonspeler values (17, 'Willy',      'Deuze',          120302);
insert into badmintonspeler values (18, 'Rick',       'Pruis',          2719102);
insert into badmintonspeler values (19, 'Henriette',  'van Delden',     130028);
insert into badmintonspeler values (20, 'Evelien',    'de Jonge',       192787);
insert into badmintonspeler values (21, 'Andre',      'Jungman',        192788);
insert into badmintonspeler values (22, 'Marc',       'Slagter',        1706175);
insert into badmintonspeler values (23, 'Jildau',     'van Netten',     1418227);
insert into badmintonspeler values (24, 'Jolanda',    'Kuipers',        122174);
insert into badmintonspeler values (25, 'Dieuwke',    'Boosman',        363605);
